---
title: "Notes on the Foundations Readings"
description: |
  In thie blog post, I try to figure out a process for thinking and writing about the readings for the upcoming class.
author:
  - name: Josh Nagel 
    url: 
    affiliation: Baruch College & The Graduate Center, CUNY
    affiliation_url: https://baruch.cuny.edu
date: 09-03-2020
output:
  distill::distill_article:
    self_contained: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

# Learn more about creating blogs with Distill at:
# https://rstudio.github.io/distill/blog.html

```

# Miller (1956)

I was excited to read this article, considering how foundational it is to memory research. Yet, I found it a surprising read - it did not describe the findings of 7 +- 2 as I expected it too. 

# Newell (1973)

I'm not sure what Newell's problem is. Why do we need an overarching theory of everything to knit all cognitive research together? Asking 20 questions does not seem to be a huge problem for me, as that is a practical way to get to understanding the complex world around us. 

# Schacter et al. (1978)

While it is interesting to read how Semon was able to predict and anticipate a lot of the findings on memory, I'm not so in love with his theory as the authors are. Considering some of the limitations of the theory, new theories are welcome to build off of his early thinking to deal with those limitations. 